/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5eb0390982f82d390e783cc3
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// ACTOR
export const RESET_ACTOR = "RESET_ACTOR";
export const CREATE_ACTOR_SUCCESS = "CREATE_ACTOR_SUCCESS";
export const DELETE_ACTOR_SUCCESS = "DELETE_ACTOR_SUCCESS";
export const GET_ACTOR_SUCCESS = "GET_ACTOR_SUCCESS";
export const LIST_ACTOR_SUCCESS = "LIST_ACTOR_SUCCESS";
export const UPDATE_ACTOR_SUCCESS = "UPDATE_ACTOR_SUCCESS";

// FILM
export const RESET_FILM = "RESET_FILM";
export const CREATE_FILM_SUCCESS = "CREATE_FILM_SUCCESS";
export const DELETE_FILM_SUCCESS = "DELETE_FILM_SUCCESS";
export const FINDBYCAST_FILM_SUCCESS = "FINDBYCAST_FILM_SUCCESS";
export const FINDBYFILMMAKER_FILM_SUCCESS = "FINDBYFILMMAKER_FILM_SUCCESS";
export const GET_FILM_SUCCESS = "GET_FILM_SUCCESS";
export const LIST_FILM_SUCCESS = "LIST_FILM_SUCCESS";
export const UPDATE_FILM_SUCCESS = "UPDATE_FILM_SUCCESS";

// FILMMAKER
export const RESET_FILMMAKER = "RESET_FILMMAKER";
export const CREATE_FILMMAKER_SUCCESS = "CREATE_FILMMAKER_SUCCESS";
export const DELETE_FILMMAKER_SUCCESS = "DELETE_FILMMAKER_SUCCESS";
export const GET_FILMMAKER_SUCCESS = "GET_FILMMAKER_SUCCESS";
export const LIST_FILMMAKER_SUCCESS = "LIST_FILMMAKER_SUCCESS";
export const UPDATE_FILMMAKER_SUCCESS = "UPDATE_FILMMAKER_SUCCESS";

// USER
export const RESET_USER = "RESET_USER";
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
